server.port=8073
eureka.client.service-url.defaultZone=http://discovery-server/eureka/

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=document-db

# Si l'authentification est activ�e dans MongoDB :
#spring.data.mongodb.username=ton_nom_utilisateur
#spring.data.mongodb.password=ton_mot_de_passe