server.port=8073

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=springbootApi

# Si l'authentification est activée dans MongoDB :
#spring.data.mongodb.username=ton_nom_utilisateur
#spring.data.mongodb.password=ton_mot_de_passe

eureka.client.service-url.defaultZone=http://localhost:8090/eureka/