server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server/eureka/
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: default-root
          uri: http://users:8070
          predicates:
            - Path=/
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/users/**

        - id: notifications
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/notifications/**

        - id: documents
          uri: lb://DOCUMENTS
          predicates:
            - Path=/documents/**

        - id: docGeneration
          uri: lb://DOCGENERATION
          predicates:
            - Path=/docGeneration/**

        - id: config-server
          uri: lb://CONFIGSERVER
          predicates:
            - Path=/config/**

        - id: eureka-server
          uri: http://discovery-server:8090
          predicates:
            - Path=/eureka-server/**